import OpenAI from "openai";
import 'dotenv/config';
import { salesManagerPrompt } from "./prompts.js";
import { get_sales_data, tools } from "./tools.js";

const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
})


export async function makeLlmCall(input) {
    let response = await client.responses.create({
        model: "gpt-4o-mini",
        instructions: salesManagerPrompt,
        input: input,
        tools: tools,
    })
    // console.log('response', response);

    input = `${input}\n\n${response.output}`
    let toolResults = [];
    for (const item of response.output) {
        if (item.type !== "function_call") continue;

        if (item.name === "get_sales_data") {
            // 3. Execute the function logic for get_sales_data
            const { product_name, start_date } = JSON.parse(item.arguments);
            const sales_data = get_sales_data({ product_name, start_date });

            // 4. Provide function call results to the model
            toolResults.push({
                type: "function_call_output",
                call_id: item.call_id,
                output: JSON.stringify(sales_data),
            })
        }
    }
    // console.log("Final input:");
    // console.log(toolResults);

    response = await client.responses.create({
        model: "gpt-4o-mini",
        instructions: "Respond only with a Get sales data generated by a tool.",
        tools,
        input: toolResults,
        previous_response_id: response.id,
    });

    // 5. The model should be able to give a response!
    // console.log("Final output:");
    // console.log(response);

    return response.output_text
}

