import OpenAI from "openai";
import 'dotenv/config';
import { salesManagerPrompt } from "./prompts.js";
import { get_inventory_data, get_products, get_sales_data, tools } from "./tools.js";

const client = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
})

const toolMap = {
    get_sales_data: get_sales_data,
    get_inventory_data: get_inventory_data,
    get_products: get_products
}

export async function makeLlmCall(input) {
    let response = await client.responses.create({
        model: "gpt-4o-mini",
        instructions: salesManagerPrompt,
        input: input,
        tools: tools,
    })
    console.log('response', response);

    input = `${input}\n\n${response.output}`
    let toolResults = [];
    for (const item of response.output) {
        if (item.type !== "function_call") continue;

        const toolFunction = toolMap[item.name];
        if (toolFunction) {
            // 3. Execute the function logic for the matched tool
            const args = JSON.parse(item.arguments);
            const result = toolFunction(args);

            // 4. Provide function call results to the model
            toolResults.push({
                type: "function_call_output",
                call_id: item.call_id,
                output: JSON.stringify(result),
            })
        }
    }
    // console.log("Final input:");
    // console.log(toolResults);

    response = await client.responses.create({
        model: "gpt-4o-mini",
        instructions: "Respond only with a Get sales data generated by a tool.",
        tools,
        input: toolResults,
        previous_response_id: response.id,
    });

    // 5. The model should be able to give a response!
    // console.log("Final output:");
    // console.log(response);

    return response.output_text
}

